[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/vimproc'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'tacroe/unite-mark'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'LeafCage/foldCC'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ssh0/easyreading.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'thinca/vim-splash'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'tyru/markdown-codehl-onthefly.vim'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'lambdalisue/vim-gista'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'moznion/hateblo.vim'

[[plugins]]
repo = 'mattn/googlesuggest-complete-vim'

[[plugins]]
repo = 'Lokaltog/powerline-fontpatcher'

[[plugins]]
repo = 'ssh0/easy-reading.vim'
